services:
  postgres-sellit:
    image: postgres:16
    container_name: db-sellit
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data


  redis:
    image: redis:alpine
    container_name: redis-sellit
    ports:
      - '6379:6379'

  web:
    build: .
    container_name: django-sellit
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      - media_volume:/app/uploads
    environment:
      - DJANGO_ENV=${DJANGO_ENV}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - CELERY_BROKER_URL=redis://redis:6379/0
    restart: always
    depends_on:
      - postgres-sellit
      - redis

  celery:
    build: .
    container_name: celery-sellit
    volumes:
      - .:/app
    environment:
      - DJANGO_ENV=${DJANGO_ENV}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: celery -A project worker --loglevel=info
    restart: always
    depends_on:
      - redis
      - postgres-sellit

  celery-beat:
    build: .
    container_name: celery-beat-sellit
    volumes:
      - .:/app
    environment:
      - DJANGO_ENV=${DJANGO_ENV}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: celery -A project beat --loglevel=info
    depends_on:
      - redis
      - postgres-sellit

volumes:
  pg_data:
  media_volume: